-- Test schema for H2 database compatibility
-- H2 doesn't support PostgreSQL arrays, so we'll use VARCHAR with JSON-like format

CREATE TABLE news
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id      VARCHAR(255) UNIQUE NOT NULL,
    title           TEXT                NOT NULL,
    link            VARCHAR(2048)       NOT NULL,
    keywords        TEXT,
    creator         TEXT,
    video_url       VARCHAR(2048),
    description     TEXT,
    content         TEXT,
    pub_date        TIMESTAMP,
    source_icon     VARCHAR(2048),
    source_name     VARCHAR(255),
    source_url      VARCHAR(2048),
    source_priority INTEGER,
    country         TEXT,
    category        TEXT,
    language        VARCHAR(10),
    coin_mentioned  TEXT,
    sentiment       VARCHAR(20),
    ai_tag          TEXT,
    duplicate       BOOLEAN                      DEFAULT FALSE NOT NULL,
    created_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_news_article_id ON news (article_id);
CREATE INDEX idx_news_pub_date ON news (pub_date);
CREATE INDEX idx_news_source_name ON news (source_name);
CREATE INDEX idx_news_language ON news (language);
CREATE INDEX idx_news_sentiment ON news (sentiment);
CREATE INDEX idx_news_duplicate ON news (duplicate);
CREATE INDEX idx_news_created_at ON news (created_at);
